### ISSUE TITLE
Redstone rendering wrongly

### ISSUE THREAD

**Issue by MagikEh** [BTW-Community/Dawn-Library#2]
User [Kamalu on discord](https://discord.com/channels/252863009590870017/445275138804416513/845050684180004914) noticed that when having only the addon api v1.1.4 and BTW installed to vMC 1.5.2 the redstone rendering was rotated funny. Redstone was still working as expected, however just looked wrong.

![Redstone Rendering Squidwards](https://cdn.discordapp.com/attachments/445275138804416513/845050683991785532/2021-05-20_23.23.22.png)

**Comment by LEUAAL** [comment]
I tested that all the way back to the 1.0.0 API....same deal

Kamalu

**Comment by ammoore00** [comment]
Fixed for next release
